// src/components/LiveGraph.tsx
/**
 * (c) 2023, Center for Computational Thinking and Design at Aarhus University and contributors
 * Modifications (c) 2024, Micro:bit Educational Foundation and contributors
 *
 * SPDX-License-Identifier: MIT
 */
import { HStack, usePrevious } from "@chakra-ui/react";
import { useSize } from "@chakra-ui/react-use-size";
import { AccelerometerDataEvent } from "@microbit/microbit-connection";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { SmoothieChart, TimeSeries } from "@microbit/smoothie";
import { useAccelerometerListener } from "../hooks/use-accelerometer-listener";
import { useDataConnected } from "../data-connection-flow";
import { useGraphColors } from "../hooks/use-graph-colors";
import { maxAccelerationScaleForGraphs } from "../mlConfig";
import { useSettings, useStore } from "../store";
import LiveGraphLabels from "./LiveGraphLabels";
import { useGraphLineStyles } from "../hooks/use-graph-line-styles";

export const smoothenDataPoint = (curr: number, next: number) => {
  // TODO: Factor out so that recording graph can do the same
  // Remove dividing by 1000 operation once it gets moved to connection lib
  return (next / 1000) * 0.25 + curr * 0.75;
};

const LiveGraph = () => {
  const isConnected = useDataConnected();
  const [{ graphColorScheme, graphLineScheme, graphLineWeight }] =
    useSettings();

  const colors = useGraphColors(graphColorScheme);
  const lineStyles = useGraphLineStyles(graphLineScheme);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  // When we update the chart we re-run the effect that syncs it with the connection state.
  const [chart, setChart] = useState<SmoothieChart | undefined>(undefined);
  const lineWidth = graphLineWeight === "default" ? 2 : 3;

  const liveGraphContainerRef = useRef(null);
  const { width, height } = useSize(liveGraphContainerRef) ?? {
    width: 100,
    height: 100,
  };

  const lineX = useMemo(() => new TimeSeries(), []);
  const lineY = useMemo(() => new TimeSeries(), []);
  const lineZ = useMemo(() => new TimeSeries(), []);
  const recordLines = useMemo(() => new TimeSeries(), []);

  // On mount draw smoothieChart
  useEffect(() => {
    if (!canvasRef.current) {
      return;
    }
    const smoothieChart = new SmoothieChart({
      maxValue: maxAccelerationScaleForGraphs,
      minValue: -maxAccelerationScaleForGraphs,
      millisPerPixel: 7,
      grid: {
        fillStyle: "#ffffff00",
        strokeStyle: "rgba(48,48,48,0.20)",
        millisPerLine: 3000,
        borderVisible: false,
      },
      interpolation: "linear",
      enableDpiScaling: false,
    });

    smoothieChart.addTimeSeries(lineX, {
      lineWidth,
      strokeStyle: colors.x,
      lineDash: lineStyles.x,
    });
    smoothieChart.addTimeSeries(lineY, {
      lineWidth,
      strokeStyle: colors.y,
      lineDash: lineStyles.y,
    });
    smoothieChart.addTimeSeries(lineZ, {
      lineWidth,
      strokeStyle: colors.z,
      lineDash: lineStyles.z,
    });

    smoothieChart.addTimeSeries(recordLines, {
      lineWidth: 3,
      strokeStyle: "#4040ff44",
      fillStyle: "#0000ff07",
    });
    setChart(smoothieChart);
    smoothieChart.streamTo(canvasRef.current, 0);
    smoothieChart.render();
    return () => {
      smoothieChart.stop();
    };
  }, [
    colors.x,
    colors.y,
    colors.z,
    lineStyles.x,
    lineStyles.y,
    lineStyles.z,
    lineWidth,
    lineX,
    lineY,
    lineZ,
    recordLines,
  ]);

  useEffect(() => {
    if (isConnected) {
      chart?.start();
    } else {
      chart?.stop();
    }
  }, [chart, isConnected]);

  // Draw on graph to display that users are recording.
  const isRecording = useStore((s) => s.isRecording);
  const prevIsRecording = usePrevious(isRecording);
  useEffect(() => {
    if (isRecording) {
      // Set the start recording line
      const now = new Date().getTime();
      recordLines.append(now - 1, -maxAccelerationScaleForGraphs, false);
      recordLines.append(now, maxAccelerationScaleForGraphs, false);
    } else if (prevIsRecording) {
      // Set the end recording line
      const now = new Date().getTime();
      recordLines.append(now - 1, maxAccelerationScaleForGraphs, false);
      recordLines.append(now, -maxAccelerationScaleForGraphs, false);
    }
  }, [isRecording, prevIsRecording, recordLines]);

  const dataRef = useRef<{ x: number; y: number; z: number }>({
    x: 0,
    y: 0,
    z: 0,
  });

  const accelerometerListener = useCallback(
    ({ data }: AccelerometerDataEvent) => {
      const t = new Date().getTime();
      dataRef.current = {
        x: smoothenDataPoint(dataRef.current.x, data.x),
        y: smoothenDataPoint(dataRef.current.y, data.y),
        z: smoothenDataPoint(dataRef.current.z, data.z),
      };
      lineX.append(t, dataRef.current.x, false);
      lineY.append(t, dataRef.current.y, false);
      lineZ.append(t, dataRef.current.z, false);
    },
    [lineX, lineY, lineZ]
  );

  useAccelerometerListener(accelerometerListener);

  return (
    <HStack
      ref={liveGraphContainerRef}
      width="100%"
      height="100%"
      overflow="hidden"
    >
      <canvas
        ref={canvasRef}
        height={height}
        id="smoothie-chart"
        width={width - 30}
      />
      {isConnected && <LiveGraphLabels />}
    </HStack>
  );
};

export default LiveGraph;

// src/components/graphs/LiveGraph.svelte
<!--
  (c) 2023, Center for Computational Thinking and Design at Aarhus University and contributors
 
  SPDX-License-Identifier: MIT
 -->

<script lang="ts">
  import { SmoothieChart, TimeSeries } from 'smoothie';
  import { onMount } from 'svelte';
  import { get } from 'svelte/store';
  import { currentData, settings } from '../../script/stores/mlStore';
  import { state } from '../../script/stores/uiStore';
  import DimensionLabels from './DimensionLabels.svelte';

  // Updates width to ensure that the canvas fills the whole screen
  export let width: number;

  var canvas: HTMLCanvasElement | undefined = undefined;
  var chart: SmoothieChart | undefined;
  let lineX = new TimeSeries();
  let lineY = new TimeSeries();
  let lineZ = new TimeSeries();
  let recordLines = new TimeSeries();
  const lineWidth = 2;

  // On mount draw smoothieChart
  onMount(() => {
    chart = new SmoothieChart({
      maxValue: 2.3,
      minValue: -2,
      millisPerPixel: 7,
      grid: {
        fillStyle: '#ffffff00',
        strokeStyle: 'rgba(48,48,48,0.20)',
        millisPerLine: 3000,
        borderVisible: false,
      },
      interpolation: 'linear',
    });

    chart.addTimeSeries(lineX, { lineWidth, strokeStyle: '#f9808e' });
    chart.addTimeSeries(lineY, { lineWidth, strokeStyle: '#80f98e' });
    chart.addTimeSeries(lineZ, { lineWidth, strokeStyle: '#808ef9' });
    chart.addTimeSeries(recordLines, {
      lineWidth: 3,
      strokeStyle: '#4040ff44',
      fillStyle: '#0000ff07',
    });
    chart.streamTo(<HTMLCanvasElement>canvas, 0);
    return () => chart?.stop();
  });

  $: {
    if ($state.isInputConnected) {
      chart?.start();
    } else {
      chart?.stop();
    }
  }

  // Draw on graph to display that users are recording
  // The jagged edges problem is caused by repeating the recordingStarted function.
  // We will simply block the recording from starting, while it's recording
  let blockRecordingStart = false;
  $: recordingStarted($state.isRecording || $state.isTesting);

  // Function to clearly diplay the area in which users are recording
  function recordingStarted(isRecording: boolean): void {
    if (!isRecording || blockRecordingStart) {
      return;
    }

    // Set start line
    recordLines.append(new Date().getTime() - 1, -2, false);
    recordLines.append(new Date().getTime(), 2.3, false);

    // Wait a second and set end line
    blockRecordingStart = true;
    setTimeout(() => {
      recordLines.append(new Date().getTime() - 1, 2.3, false);
      recordLines.append(new Date().getTime(), -2, false);
      blockRecordingStart = false;
    }, get(settings).duration);
  }

  $: {
    const t = new Date().getTime();
    lineX.append(t, $currentData.x, false);
    lineY.append(t, $currentData.y, false);
    lineZ.append(t, $currentData.z, false);
  }
</script>

<div class="flex overflow-hidden">
  <canvas bind:this={canvas} height={160} id="smoothie-chart" width={width - 30} />
  <DimensionLabels />
</div>
