// src/components/AboutDialog.tsx
/**
 * (c) 2024, Micro:bit Educational Foundation and contributors
 *
 * SPDX-License-Identifier: MIT
 */
import {
  AspectRatio,
  Box,
  Button,
  HStack,
  Icon,
  Image,
  Link,
  Modal,
  ModalBody,
  ModalCloseButton,
  ModalContent,
  ModalFooter,
  ModalOverlay,
  SimpleGrid,
  Table,
  TableCaption,
  Tbody,
  Td,
  Text,
  Tr,
  useClipboard,
  VisuallyHidden,
  VStack,
} from "@chakra-ui/react";
import { ReactNode } from "react";
import { RiFileCopy2Line, RiGithubFill } from "react-icons/ri";
import { FormattedMessage, useIntl } from "react-intl";
import { useDeployment } from "../deployment";
import aarhusLogo from "../images/aulogo_uk_var2_blue.png";
import microbitHeartImage from "../images/microbit-heart.png";

interface AboutDialogProps {
  isOpen: boolean;
  onClose: () => void;
  finalFocusRef?: React.RefObject<HTMLButtonElement>;
}

/**
 * An about dialog with version information.
 */
const AboutDialog = ({ isOpen, onClose, finalFocusRef }: AboutDialogProps) => {
  const { appNameFull, OrgLogo } = useDeployment();
  const versionInfo = [
    {
      name: appNameFull,
      value: import.meta.env.VITE_VERSION,
      href: "https://github.com/microbit-foundation/ml-trainer",
    },
  ];

  const clipboardVersion = versionInfo
    .map((x) => `${x.name} ${x.value}`)
    .join("\n");

  const { hasCopied, onCopy } = useClipboard(clipboardVersion);
  const intl = useIntl();
  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      size={{ base: "full", md: "2xl" }}
      finalFocusRef={finalFocusRef}
    >
      <ModalOverlay>
        <ModalContent>
          <ModalBody>
            <ModalCloseButton />
            <VStack spacing={8} pl={5} pr={5} pt={5}>
              <HStack justifyContent="center" gap={8}>
                {OrgLogo && <OrgLogo fill="#000" color="black" height={55} />}
                <Image
                  src={aarhusLogo}
                  h="55px"
                  alt={intl.formatMessage({ id: "aarhus-university-alt" })}
                />
              </HStack>
              <Text textAlign="center">
                <FormattedMessage
                  id="about-dialog-title"
                  values={{
                    link: (chunks: ReactNode) => (
                      <Link
                        color="brand.600"
                        textDecoration="underline"
                        href="https://cctd.au.dk/"
                        target="_blank"
                        rel="noopener"
                      >
                        {chunks}
                      </Link>
                    ),
                  }}
                />
              </Text>
              <SimpleGrid columns={[1, 1, 2, 2]} spacing={8}>
                <Box>
                  <AspectRatio
                    ml="auto"
                    mr="auto"
                    ratio={690 / 562}
                    maxWidth={[388, 388, null, null]}
                  >
                    <Image
                      src={microbitHeartImage}
                      alt={intl.formatMessage({ id: "about-dialog-alt" })}
                    />
                  </AspectRatio>
                </Box>
                <VStack alignItems="center" justifyContent="center" spacing={4}>
                  <Table size="sm" sx={{ fontVariantNumeric: "unset" }}>
                    <Tbody>
                      {versionInfo.map((v) => (
                        <Tr key={v.name}>
                          <Td>{v.name}</Td>
                          <Td>{v.value}</Td>
                          <Td padding={0}>
                            {/* Move padding so we get a reasonable click target. */}
                            <Link
                              display="block"
                              pl={4}
                              pr={4}
                              pt={2}
                              pb={2}
                              target="_blank"
                              rel="noopener noreferrer"
                              href={v.href}
                            >
                              <Icon as={RiGithubFill} />
                              <VisuallyHidden>GitHub</VisuallyHidden>
                            </Link>
                          </Td>
                        </Tr>
                      ))}
                    </Tbody>
                    <TableCaption color="gray.800" placement="top">
                      <FormattedMessage id="software-versions" />
                    </TableCaption>
                  </Table>
                  <Button
                    leftIcon={<RiFileCopy2Line />}
                    onClick={onCopy}
                    size="md"
                  >
                    <FormattedMessage
                      id={hasCopied ? "copied" : "copy-action"}
                    />
                  </Button>
                </VStack>
              </SimpleGrid>
            </VStack>
          </ModalBody>
          <ModalFooter>
            <Button onClick={onClose} variant="primary" size="lg">
              <FormattedMessage id="close-action" />
            </Button>
          </ModalFooter>
        </ModalContent>
      </ModalOverlay>
    </Modal>
  );
};

export default AboutDialog;

// src/components/control-bar/control-bar-items/AboutDialog.svelte
<!--
  (c) 2023, Center for Computational Thinking and Design at Aarhus University and contributors

  SPDX-License-Identifier: MIT
 -->

<script lang="ts">
  import StandardButton from '../../StandardButton.svelte';
  import microbitLogo from '../../../imgs/microbit-logo-black.svg';
  import microbitHeartImage from '../../../imgs/microbit-heart.png';
  import aarhusLogo from '../../../imgs/aulogo_uk_var2_blue.png';
  import GitHubIcon from 'virtual:icons/ri/github-fill';
  import { t } from '../../../i18n';
  import HtmlFormattedMessage, {
    linkWithProps as linkWithProps,
  } from '../../HtmlFormattedMessage.svelte';
  import Dialog from '../../dialogs/StandardDialog.svelte';

  export let onClose: () => void;
  export let isOpen: boolean;
</script>

<Dialog {isOpen} {onClose}>
  <div class="flex flex-col gap-5 w-150 text-black">
    <div class="flex flex-col gap-8">
      <div class="grid grid-cols-2 gap-20 items-center">
        <img src={microbitLogo} alt="micro:bit" />
        <img src={aarhusLogo} alt="Aarhus" />
      </div>
      <p class="text-center">
        <HtmlFormattedMessage
          id="about.developedInPartnership"
          options={{
            values: {
              link: linkWithProps({
                href: 'https://cctd.au.dk/',
                target: '_blank',
                rel: 'noopener',
              }),
            },
          }} />
      </p>
      <div class="grid grid-cols-2 gap-5 items-center text-center">
        <img
          class="w-290px h-236px"
          src={microbitHeartImage}
          alt={$t('about.microbitHeartImageAlt')} />
        <table class="text-sm">
          <tbody
            ><tr class="divide-gray-100"
              ><td>{$t('content.index.title')}</td><td
                >{import.meta.env.VITE_APP_VERSION}</td
              ><td
                ><a
                  target="_blank"
                  rel="noopener noreferrer"
                  href="https://github.com/microbit-foundation/ml-trainer"
                  class="inline-flex items-center outline-none focus-visible:ring-4 focus-visible:ring-offset-1 focus-visible:ring-ring"
                  ><GitHubIcon /><span class="sr-only">GitHub</span></a>
              </td></tr
            ></tbody
          ><caption class="p-2">{$t('about.softwareVersions')}</caption>
        </table>
      </div>
    </div>
    <div class="flex justify-end">
      <StandardButton onClick={onClose} type="primary"
        >{$t('actions.close')}</StandardButton>
    </div>
  </div>
</Dialog>
