// src/components/connection-prompt/arrows/ArrowTwo.svelte
<!--
  (c) 2024, Center for Computational Thinking and Design at Aarhus University and contributors

  SPDX-License-Identifier: MIT
 -->

<svg
  width="166"
  height="180"
  viewBox="0 0 166 180"
  fill="none"
  xmlns="http://www.w3.org/2000/svg">
  <rect x="13" y="25" width="146" height="10" fill="#7BCDC2" />
  <rect x="13" y="25" width="10" height="140" fill="#7BCDC2" />
  <circle cx="146" cy="30" r="20" fill="#7BCDC2" />
  <path d="M17.5 180L2.34455 143.75H32.6554L17.5 180Z" fill="#7BCDC2" />
  <foreignObject x="126" y="10" width="40" height="40">
    <div class="h-10 w-10 flex items-center justify-center" aria-hidden>
      <p class="text-2xl text-white">2</p>
    </div>
  </foreignObject>
</svg>

// src/components/ArrowTwo.tsx
/**
 * (c) 2024, Micro:bit Educational Foundation and contributors
 *
 * SPDX-License-Identifier: MIT
 */
import { Box, Text, token } from "../shared-ui";

const ArrowTwo = () => {
  const brand500 = token("colors.brand2.500");
  return (
    <svg
      width="244"
      height="180"
      viewBox="0 0 244 180"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect x="25" y="25" width="180" height="10" fill={brand500} />
      <rect x="25" y="25" width="10" height="120" fill={brand500} />
      <circle cx="202" cy="30" r="20" fill={brand500} />
      <path d="M30 170 L14.84455 133.75 H45.1554 L30 170Z" fill={brand500} />
      <foreignObject x="182" y="10" width="40" height="40">
        <Box
          aria-hidden
          height="40px"
          width="40px"
          display="flex"
          alignItems="center"
          justifyContent="center"
        >
          <Text fontSize="2xl" color="white">
            2
          </Text>
        </Box>
      </foreignObject>
    </svg>
  );
};
export default ArrowTwo;
