// src/components/connection-prompt/bluetooth/ConnectBatteryDialog.svelte
<!--
  (c) 2023, Center for Computational Thinking and Design at Aarhus University and contributors

  SPDX-License-Identifier: MIT
 -->

<script lang="ts">
  import StandardButton from '../../StandardButton.svelte';
  import ExternalLinkIcon from 'virtual:icons/ri/external-link-line';
  import { t } from '../../../i18n';
  import microbitConnectedImage from '../../../imgs/stylised-microbit-connected.svg';
  import DialogHeading from '../../DialogHeading.svelte';

  export let onNextClick: () => void;
  export let onBackClick: () => void;
</script>

<div class="w-175">
  <DialogHeading>
    {$t('connectMB.connectBattery.heading')}
  </DialogHeading>
  <div class="space-y-5">
    <p>{$t('connectMB.connectBattery.subtitle')}</p>
    <img src={microbitConnectedImage} alt="" class="w-68 h-229px m-auto" />
    <a
      class="inline-flex mr-auto gap-x-1 items-center text-link outline-none focus-visible:ring-4 focus-visible:ring-offset-1 focus-visible:ring-ring"
      href="https://support.microbit.org/support/home"
      target="_blank"
      rel="noopener">
      {$t('connectMB.connectBattery.link')}
      <ExternalLinkIcon />
    </a>
  </div>
</div>
<div class="flex justify-end gap-x-5 pt-5">
  <StandardButton onClick={onBackClick}>{$t('connectMB.backButton')}</StandardButton>
  <StandardButton type="primary" onClick={onNextClick}
    >{$t('connectMB.nextButton')}</StandardButton>
</div>

// src/components/ConnectBatteryDialog.tsx
import { Icon, Image, Link, Text, VStack } from "@chakra-ui/react";
import { FormattedMessage } from "react-intl";
import microbitConnectedImage from "../images/stylised-microbit-connected.svg";
import ConnectContainerDialog, {
  ConnectContainerDialogProps,
} from "./ConnectContainerDialog";
import { RiExternalLinkLine } from "react-icons/ri";

export interface ConnectBatteryDialogProps
  extends Omit<ConnectContainerDialogProps, "children" | "headingId"> {}

const ConnectBatteryDialog = ({ ...props }: ConnectBatteryDialogProps) => {
  return (
    <ConnectContainerDialog
      headingId="connectMB.connectBattery.heading"
      {...props}
    >
      <VStack gap={5} width="100%">
        <Text alignSelf="left" width="100%">
          <FormattedMessage id="connectMB.connectBattery.subtitle" />
          <Link
            color="blue.600"
            //TODO: Replace with real support link.
            href="https://support.microbit.org/support/home"
            target="_blank"
            rel="noopener"
            display="flex"
            flexDirection="row"
            gap={1}
          >
            <FormattedMessage id="connectMB.connectBattery.link" />
            <Icon
              as={RiExternalLinkLine}
              boxSize={5}
              color="blue.600"
              position="relative"
            />
          </Link>
        </Text>
        <Image
          height="229px"
          width="16rem"
          src={microbitConnectedImage}
          alt=""
        />
      </VStack>
    </ConnectContainerDialog>
  );
};

export default ConnectBatteryDialog;
